
        // Generated JS for Home, you may or may not touch this file
        // Auto generated by the sIDE framework

        document.addEventListener("DOMContentLoaded", () => {
            console.log("Welcome to Home!");
        });
        