# sIDE/framework/parsers/cssParser.py

#--- Framework Modules ---
from framework.modules.textFormat import log, nextLine
#----------------------------

import os

def render_css(window, output_dir):
    """
    Renders and generates a CSS file for the given window.
    """

    try :
        # Creates the output folder
        os.makedirs(output_dir, exist_ok=True)

        formatted_fileName = window.title.replace(" ", "_").lower() # Text formatting into a valid file name
        file_path = os.path.join(output_dir, f"{formatted_fileName}.css")

        # Defines the CSS content
        css_content = f"""
        /* Generated CSS for {window.title}, you may or may not touch this file */
        /* Auto generated by the sIDE framework */


        #window {{
            width: {window.width}px;
            height: {window.height}px;
            border: 1px solid #000;
            box-sizing: border-box;
            padding: 10px;
            overflow: auto;
        }}

        body {{
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }}
        """
        # Writes the CSS content to the file
        with open(file_path, "w") as f:
            f.write(css_content)

    except Exception as e:
        log("red", f"Error generating CSS file: {e}")

    else:
        log("green", f"CSS file generated: {file_path}")