# sIDE/framework/parsers/htmlParser.py

#--- Framework Modules ---
from framework.modules.textFormat import log, nextLine
#----------------------------

import os

def render_html(window, output_dir):
    """
    Renders and generates an HTML file for the given window.
    """
    try :
        # Creates the output folder
        os.makedirs(output_dir, exist_ok=True)

        formatted_fileName = window.title.replace(" ", "_").lower() # Text formatting into a valid file name
        file_path = os.path.join(output_dir, f"{formatted_fileName}.html")
    
        # Defines the HTML content
        html_content = f"""
        <!DOCTYPE html>

        <!-- Generated HTML for {window.title}, you may or may not touch this file -->
        <!-- Auto generated by the sIDE framework -->
  
        <html>
        <head>
            <meta charset="UTF-8">
            <title>{window.title}</title>

            <!-- Link to the CSS file -->
            <link rel="stylesheet" href="{formatted_fileName}.css">

            <!-- Link to the JS file -->
            <script src="{formatted_fileName}.js" defer></script>

        </head>
        <body>
            <div id="app" style="width: {window.width}px; height: {window.height}px;">
                <h1>Welcome to {window.title}</h1>
                <p>This is a sample window with dimensions {window.width}x{window.height}.</p>

                <!-- Additional UI elements can be added here -->
            </div>
        </body>
        </html>
        """

        # Writes the HTML content to the file
        with open(file_path, "w") as f:
            f.write(html_content)

    except Exception as e:
        log("red", f"Error generating HTML file: {e}")

    else :
        log("green", f"HTML file generated: {file_path}")