# sIDE/framework/parsers/jsParser.py

#--- Framework Modules ---
from framework.modules.textFormat import log, nextLine
#----------------------------

import os

def render_js(window, output_dir):
    """
    Renders and generates a JS file for the given window.
    """
    try :
        # Creates the output folder
        os.makedirs(output_dir, exist_ok=True)

        formatted_fileName = window.title.replace(" ", "_").lower() # Text formatting into a valid file name
        file_path = os.path.join(output_dir, f"{formatted_fileName}.js")

        # Defines the JS content
        js_content = f"""
        // Generated JS for {window.title}, you may or may not touch this file
        // Auto generated by the sIDE framework

        document.addEventListener("DOMContentLoaded", () => {{
            console.log("Welcome to {window.title}!");
        }});
        """
        # Writes the JS content to the file
        with open(file_path, "w") as f:
            f.write(js_content)

    except Exception as e:
        log("red", f"Error generating JS file: {e}")
    else:
        log("green", f"JS file generated: {file_path}")